config/routes.rb
Rails.application.routes.draw do
  
  mount Blacklight::Engine => '/'
  Blacklight::Marc.add_routes(self)
  root to: "catalog#index"
    concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
  end

  devise_for :users, controllers: { registrations: 'registrations' }
  
  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  resource :download, as: "download", path: "/download", controller: "download"
  get "download/peaks" => "download#peaks"

  get "input_form" => "input_form#index"
  resource :input_form, as: "input_form", path: "/input_form", controller: "input_form"

  get "input_form/samples" => "input_form#samples"
  get "input_form/samples/autocomplete"
  get "input_form/upload"
  get "/populate-plants" => "input_form#plant_select"
  get "/populate-ingredients" => "input_form#ingredient_select"
  get "input_form/sites" => "input_form#site_select"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :people, foreign_key: :oa_id
  has_many :samples, foreign_key: :oa_id

  def self.new_oa_id
    oa_id = Team.last.oa_id.sub(/\d+$/) {|d| (d.to_i + 1).to_s}
  end

  def self.new_member(vals_hash)
    @team = Team.create(vals_hash)
  end
end

app/controllers/catalog_controller.rb
# -*- encoding : utf-8 -*-
class CatalogController < ApplicationController  

  include Blacklight::Catalog

  configure_blacklight do |config|
    ## Class for sending and receiving requests from a search index
     config.repository_class = Blacklight::Solr::Repository
    #
    ## Class for converting Blacklight's url parameters to into request parameters for the search index
     config.search_builder_class = ::SearchBuilder
    #
    ## Model that maps search index responses to the blacklight response model
     config.response_model = Blacklight::Solr::Response

    ## Default parameters to send to solr for all search-like requests. See also SearchBuilder#processed_parameters
    config.default_solr_params = { 
      :qt => 'search',
      :q => '*:*',
      :rows => 10,
      :facet => true,
      :'facet.mincount' => 1
    }

    # solr path which will be added to solr base url before the other solr params.
    config.solr_path = 'select' 
    
    # items to show per page, each number in the array represent another option to choose from.
    #config.per_page = [10,20,50,100]

    ## Default parameters to send on single-document requests to Solr. These settings are the Blackligt defaults (see SearchHelper#solr_doc_params) or
    ## parameters included in the Blacklight-jetty document requestHandler.
    #
    config.default_document_solr_params = {
      :qt => 'document',
      ## These are hard-coded in the blacklight 'document' requestHandler
       :fl => '*',
       :rows => 1,
       :q => '{!raw f=oa_id v=$id}' 
    }

    # solr field configuration for search results/index views
    config.index.title_field = 'title_display'
    config.index.display_type_field = 'format'

    # solr field configuration for document/show views
    config.show.title_field = 'title_display'
    config.show.display_type_field = 'format'

    # solr fields that will be treated as facets by the blacklight application
    #   The ordering of the field names is the order of the display
    #
    # Setting a limit will trigger Blacklight's 'more' facet values link.
    # * If left unset, then all facet values returned by solr will be displayed.
    # * If set to an integer, then "f.somefield.facet.limit" will be added to
    # solr request, with actual solr request being +1 your configured limit --
    # you configure the number of items you actually want _displayed_ in a page.    
    # * If set to 'true', then no additional parameters will be sent to solr,
    # but any 'sniffed' request limit parameters will be used for paging, with
    # paging at requested limit -1. Can sniff from facet.limit or 
    # f.specific_field.facet.limit solr request params. This 'true' config
    # can be used if you set limits in :default_solr_params, or as defaults
    # on the solr side in the request handler itself. Request handler defaults
    # sniffing requires solr requests to be made with "echoParams=all", for
    # app code to actually have it echo'd back to see it.  
    #
    # :show may be set to false if you don't want the facet to be drawn in the 
    # facet bar
    config.add_facet_field 'site_facet', :label => 'Site', :limit => 10
    config.add_facet_field 'compound_facet', :label => 'Compounds', :limit => 10
    config.add_facet_field 'source_type_facet', :label => 'Vessel Type', :limit => 10
    config.add_facet_field 'ancient_ref_author_facet', :label => 'Ancient References', :limit => 10
    config.add_facet_field 'product_facet', :label => 'Products', :limit => 10
    


    #config.add_facet_field 'example_pivot_field', :label => 'Pivot Field', :pivot => ['format', 'language_facet']

    #config.add_facet_field 'example_query_facet_field', :label => 'Publish Date', :query => {
    #  :years_5 => { :label => 'within 5 Years', :fq => "pub_date:[#{Time.zone.now.year - 5 } TO *]" },
    #  :years_10 => { :label => 'within 10 Years', :fq => "pub_date:[#{Time.zone.now.year - 10 } TO *]" },
    #  :years_25 => { :label => 'within 25 Years', :fq => "pub_date:[#{Time.zone.now.year - 25 } TO *]" }
    #}


    # Have BL send all facet field names to Solr, which has been the default
    # previously. Simply remove these lines if you'd rather use Solr request
    # handler defaults, or have no facets.
    config.add_facet_fields_to_solr_request!

    # solr fields to be displayed in the index (search results) view
    #   The ordering of the field names is the order of the display 
    config.add_index_field 'sample_id', :label => 'Sample ID'
    config.add_index_field 'sample_site', :label => 'Site'
    config.add_index_field 'sample_type', :label => 'Sample Type'
    config.add_index_field 'sample_object_type', :label => 'Object Type'
    config.add_index_field 'compound_name', :label => 'Compound Name'
    config.add_index_field 'compound_formula', :label => 'Compound Formula'
    config.add_index_field 'plant_sci_name', :label => 'Plant Scientific Name'
    config.add_index_field 'plant_common_name', :label => 'Plant Common Name'
    config.add_index_field 'person_id', :label => "ID"
    config.add_index_field 'person_affiliation', :label => "Affiliation"
    config.add_index_field 'ancient_ref_author', :label => "Author Name"
    config.add_index_field 'ancient_ref_title', :label => "Work Title"
    config.add_index_field 'product_name', :label => "Product"
    config.add_index_field 'ancient_ref_product', :label => "Product Referenced"
    config.add_index_field 'source_site', :label => "Site"
    config.add_index_field 'source_relative_date', :label => "Date"

    # solr fields to be displayed in the show (single result) view
    #   The ordering of the field names is the order of the display 
    config.add_show_field 'sample_id', :label => 'Sample ID'
    config.add_show_field 'sample_site', :label => 'Site'
    config.add_show_field 'sample_locus_type', :label => 'Sample Locus Type'
    config.add_show_field 'sample_type', :label => 'Sample Type'
    config.add_show_field 'sample_object_type', :label => 'Object Type'
    config.add_show_field 'compound_id', :label => 'Compound ID'
    config.add_show_field 'compound_name', :label => 'Compound Name'
    config.add_show_field 'compound_formula', :label => 'Compound Formula'
    config.add_show_field 'plant_id', :label => 'Plant ID'
    config.add_show_field 'plant_sci_name', :label => 'Plant Scientific Name'
    config.add_show_field 'plant_common_name', :label => 'Plant Common Name'
    config.add_show_field 'site_id', :label => 'Site ID'
    config.add_show_field 'site_name', :label => 'Site Name'
    config.add_show_field 'source_id', :label => 'Source ID'
    config.add_show_field 'source_type', :label => 'Source Type'
    config.add_show_field 'source_notes', :label => 'Source Notes'
    config.add_show_field 'source_condition', :label => 'Source Condition'
    config.add_show_field 'source_url', :label => 'URL'

    # "fielded" search configuration. Used by pulldown among other places.
    # For supported keys in hash, see rdoc for Blacklight::SearchFields
    #
    # Search fields will inherit the :qt solr request handler from
    # config[:default_solr_parameters], OR can specify a different one
    # with a :qt key/value. Below examples inherit, except for subject
    # that specifies the same :qt as default for our own internal
    # testing purposes.
    #
    # The :key is what will be used to identify this BL search field internally,
    # as well as in URLs -- so changing it after deployment may break bookmarked
    # urls.  A display label will be automatically calculated from the :key,
    # or can be specified manually to be different. 

    # This one uses all the defaults set by the solr request handler. Which
    # solr request handler? The one set in config[:default_solr_parameters][:qt],
    # since we aren't specifying it otherwise. 
    
    config.add_search_field 'all_fields', :label => 'All Fields'
    

    # Now we see how to over-ride Solr request handler defaults, in this
    # case for a BL "search field", which is really a dismax aggregate
    # of Solr search fields. 

    config.add_search_field('vessel') do |field|
      field.label = "Vessel Type"
      field.solr_local_parameters = {
        :type => "dismax",
        :qf => 'source_type sample_object_type'
      }
    end
    
    config.add_search_field('plant') do |field|
      field.label = "Plant Name" 
      field.solr_local_parameters = {
        :type => 'dismax',
        :qf => 'plant_sci_name plant_common_name'
      }
    end

    config.add_search_field('compound') do |field|
      field.label = "Compounds" 
      field.solr_local_parameters = {
        :type => 'dismax',
        :qf => 'compound_name compound_formula'
      }
    end

    config.add_search_field('ancient_ref') do |field|
      field.label = "Ancient Reference" 
      field.solr_local_parameters = {
        :type => 'dismax',
        :qf => 'ancient_ref_author ancient_ref_title'
      }
    end

    # "sort results by" select (pulldown)
    # label in pulldown is followed by the name of the SOLR field to sort by and
    # whether the sort is ascending or descending (it must be asc or desc
    # except in the relevancy case).
    config.add_sort_field 'score desc', :label => 'relevance'
    

    # If there are more than this many search results, no spelling ("did you 
    # mean") suggestion is offered.
    config.spell_max = 5
    
  end

end 

app/views/catalog/_detailed_rec.html.erb
  
  <div class="panel" id="accordion">
    <div class="panel-heading" role="tab" id="detail_rec">
      <h2>
        <a data-toggle="collapse" data-parent="#accordion" href="#collapse_detail">Detailed Record</a>
      </h2>
    </div>

    <div id="collapse_detail" class="panel-collapse collapse">
      <div class="panel-body">

        <% details_hash.each do |key, value| %>
          <div class="well">
          <h3><%= key %></h3>
            <ul class="list-group">
              <% value.attributes.each do |k, v| %>
               <% unless k == "created_at" || k == "updated_at" || k == "id" || v == "" || v == nil || v == summary_info["oa_id"] %>
                  <li class="list-group-item">
                    <b><%= k.gsub("_", " ").capitalize %>: </b> 
                    <% if v =~ /oa2017/ %>
                      <%= link_to v, v %>
                    <% elsif k == "sample_quality" %>
                      <%= summary_info["sample_quality"] %>
                    <% else %>
                      <%= v %>
                    <% end %>
                  </li>
                <% end %>
              <% end %>
            </ul>
          </div>

        <% end %>
      </div>
    </div>
  </div>

app/views/catalog/_inner_list.html.erb
<%# displays the smaller, collapsable portions in the document views %>

		<div class="panel">
			<div class="panel-heading" role="tab" id="<%= "heading" + "#{num}" %>">
		       
				<dt><%= "#{name}" %></dt>
				<dd>
					<a role="button" data-toggle="collapse" data-parent="#accordion" href="<%= "#collapse" + "#{num}" %>" aria-controls="<%= "collapse" + "#{num}" %>">

		         <%= "#{data['display']}" %> 
		         <span class="glyphicon glyphicon-minus"/> 
		      </a>
		    </div>
		    <div id="<%= "collapse" + "#{num}" %>" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="<%= "heading" + "#{num}" %>">
		      <div class="panel-body">
		      	
		        <dl class="dl-horizontal  dl-invert">
		        	<% data.each do |key, val| %>
		        		<% unless val == nil || key == ""  %>
			        		<% unless key == "display" %>
			        			<dt><%= "#{key.gsub("_", " ").capitalize}" %></dt>
			        			<dd><%= key == "image_file_path" ? render_value(val, data["image_credit"]) : render_value(val) %></dd>
			        		<% end -%>
			        	<% end -%>
		        	<% end -%>

		        	<dt></dt>
		        	<dd><%= link_to "Click here to see more information", oa_id %>

		        </dl>
		      </div>
		    </div>
		  </div>

app/views/catalog/_mini_list.html.erb
<%# displays the smaller, collapsable portions in the document views %>

	<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
		<div class="panel">
			<div class="panel-heading" role="tab" id="<%= "heading" + "#{num}" %>">
		        
				<dt><%= "#{name}:" %></dt>
				<dd>
					<a role="button" data-toggle="collapse" data-parent="#accordion" href="<%= "#collapse" + "#{num}" %>" aria-controls="<%= "collapse" + "#{num}" %>">
		         <%= "#{data['display']}" %> 
		      </a>
		    </div>
		    <div id="<%= "collapse" + "#{num}" %>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="<%= "heading" + "#{num}" %>">
		      <div class="panel-body">
		      	
		        <dl class="dl-horizontal  dl-invert">
		        	<% data.each do |key, val| %>
		        		<% unless val == nil  %>
			        		<% unless key == "display" %>
			        			<dt><%= "#{key.gsub("_", " ").capitalize}:" %></dt>
			        			<dd><%= "#{val}" %></dd>
			        		<% end -%>
			        	<% end -%>
		        	<% end -%>
		        	<dt>See full record:</dt>
		        	<dd><%= link_to "Here", oa_id %> 
		        </dl>
		      </div>
		    </div>
		  </div>

app/views/catalog/_modals.html.erb
<% if defined? type %>
  <!-- Modern bib modal -->
  <div id="bib_modal_<%= type %>" class="modal fade" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">
          <% bib.each do |rec| %>
           <%= rec %> </br>
          <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

<% else %>
  <!-- Ancient Ref modal  -->
  <div id="ref_modal<%= anc_ref[0]["oa_id"] %>" class="modal fade" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body"> 
          <% anc_ref.each do |a_ref| %>
            <div class="well">
            <p><%= a_ref["excerpt_eng"] %></p>
            <p><%= a_ref["author"] if a_ref["author"] %> <%= link_to a_ref["work"], a_ref["link"], target: :_blank %>
              <% unless a_ref["link1"].nil? %>
                , <%= link_to "Link 2", a_ref["link1"], target: :_blank %>
              <% end %>
            </p>
            </div>
          <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>
<% end %>

app/views/catalog/_new_compound_show.html.erb
<% summary_info = data_hashes["show_hash"] %>

<div class="panel-group">
  <div class="panel">
    <% if data_hashes.has_key?("image_hash") %>
        <%= render :partial => "thumbnails" , :locals => {:image_hash => data_hashes["image_hash"]} %>
    <% end %>
  </div>
  <div class="panel">
    <div class="panel-heading">
      <h2>Record Summary</h2>
    </div>
    <div class="panel-body">
      <div class="well">
        <h3>Compound Information</h3> 
         <ul class="list-group">
          <li class="list-group-item"><b>Name:</b> <%= summary_info["name"] %> </li>
          <li class="list-group-item"><b>Formula:</b> <%= summary_info["formula"] %> </li>
          <li class="list-group-item"><b>Molecular Weight:</b> <%= summary_info["molecular_weight"] %> </li>
          <li class="list-group-item"><b>Chromatogram Peak Time:</b> <%= summary_info["peak_time"] %> </li>
          <li class="list-group-item">
            <a href="<%= summary_info["dukes_url"] %>" class="btn btn-success btn-xs" role="button" target="_blank">Duke's</a>
            <a href="<%= summary_info["nist_url"] %>" class="btn btn-warning btn-xs" role="button" target="_blank">NIST</a>
          </li>
        </ul>
      </div>

      <div class="well">
        <h3>Plants with Compound</h3>
         <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th>Scientific Name</th>
                  <th>Common Name</th>
                  <th>Additional Info</th>
                </tr>
              </thead>
              <tbody>
               <% data_hashes["plant_hash"].each do |key, val| %>
                  <tr>
                    <td>
                      <%= link_to val[0], key %>
                    </td>
                    <td>
                      <%= val[1] %>
                    </td>
                    <td>
                      <a href="<%= val[2] %>" class="btn btn-success btn-sm" role="button" target="_blank">Duke's</a>
                      <% unless val[3].nil? || val[3].empty? %>
                        <a href="<%= val[3] %>" class="btn btn-default btn-sm" role="button" target="_blank">Flora</a>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>

        <div class="well">
          <h3>Samples with Compound</h3>
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th>Sample ID</th>
                  <th>Site</th>
                  <th>Probable Commodity</th>
                </tr>
              </thead>
              <tbody>
               <% data_hashes["sample_hash"].each do |key, val| %>
                  <tr>
                    <td>
                      <%= link_to key, key %>
                    </td>
                    <td>
                      <%= link_to val[0][1], val[0][0] %>
                    </td>
                    <td>
                      <%= link_to val[1][0], val[1][1] %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/catalog/_new_person_show.html.erb
<% summary_info = data_hashes["show_hash"] %>
<div class="panel-group">
  <div class="panel">
    <% if data_hashes.has_key?("image_hash") %>
        <%= render :partial => "thumbnails" , :locals => {:image_hash => data_hashes["image_hash"]} %>
    <% end %>
  </div>
  <div class="panel">
    <div class="panel-heading">
      <h2>Record Summary</h2>
    </div>
    <div class="panel-body">
      <div class="well">
        <h3>Person Information</h3> 
         <ul class="list-group">
          <li class="list-group-item"><b>Name:</b> <%= summary_info["name"] %> </li>
          <li class="list-group-item"><b>Affiliation:</b> <%= summary_info["affiliation"] %> </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/catalog/_new_site_show.html.erb
<% summary_info = data_hashes["show_hash"] %>
<% director = data_hashes["director_hash"] %>

<div class="panel-group">
  <div class="panel">
    <% if data_hashes.has_key?("image_hash") %>
        <%= render :partial => "thumbnails" , :locals => {:image_hash => data_hashes["image_hash"]} %>
    <% end %>
  </div>
  <div class="panel">
    <div class="panel-heading">
      <h2>Record Summary</h2>
    </div>
    <div class="panel-body">
      <div class="well">
        <h3>Site Information</h3> 
         <ul class="list-group">
          <li class="list-group-item"><b>Site Name:</b> <%= summary_info["name"] %> </li>
          <li class="list-group-item"><b>Geographic Coordinates:</b> <%= summary_info["geo_coords"] %> 
            <% if summary_info["atlas_url"] %>
               <a href="<%= summary_info["atlas_url"] %>" class="btn btn-primary btn-xs" role="button" title="Site requires signup" target="_blank">Atlas</a>
            <% end %>
          </li>
          <li class="list-group-item"><b>Dates Excavated:</b> <%= summary_info["date"] %> </li>

          <li class="list-group-item"><b>Director:</b> <%= link_to director["first_name"]+" "+director["last_name"], director["oa_id"] %> </li>
          <li class="list-group-item"><b>Notes:</b> <%= summary_info["notes"] %> </li>
        </ul>
      </div>

      <div class="well">
        <h3>Objects Tested from Site</h3> 
        <table class="table">
          <thead>
            <tr>
              <th>Object Type</th>
              <th>Date</th>
              <th>Current Location</th>
            </tr>
          </thead>
          <% unless data_hashes["source_hash"].nil? %>
            <tbody>
              <% data_hashes["source_hash"].each do |key, val| %>
                <tr>
                  <td>
                    <%= link_to val[0], key %>
                  </td>
                  <td>
                    <%= val[1] %>
                  </td>
                  <td>
                    <%= link_to val[2], val[3] %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          <% end %>
        </table>
      </div>

      <div class="well">
        <h3>Bibliography</h3>
        <% unless data_hashes["bib_hash"].nil? %>
          <ul class="list-group">   
            <% data_hashes["bib_hash"].each do |bib| %>
              <li class="list-group-item">
                <%= bib %>
              </li>
            <% end %>          
          </ul>
        <% end %> 
      </div>
    </div>   
        
  </div>
</div>

app/views/catalog/_new_source_show.html.erb
<% summary_info = data_hashes["source_hash"] %>

<div class="panel-group">
  <div class="panel">
    <% if data_hashes.has_key?("image_hash") %>
        <%= render :partial => "thumbnails" , :locals => {:image_hash => data_hashes["image_hash"]} %>
    <% end %>
  </div>
  <div class="panel">
    <div class="panel-heading">
      <h2>Record Summary</h2>
    </div>
    <div class="panel-body">
      <div class="well">
        <h3>Source Information</h3>
         <ul class="list-group">

          <li class="list-group-item"><b>Find Site:</b> <%= link_to summary_info["site"][1], summary_info["site"][0] %> </li>
          <li class="list-group-item"><b>Relative Date:</b> <%= summary_info["date"] %> </li>
          <li class="list-group-item"><b>Object Type:</b> <%= summary_info["object_type"] %> </li>
          <li class="list-group-item"><b>Petrography:</b> <%= summary_info["petrography"] %> </li>
        </ul>
      </div>
 
      <div class="well">
        <h3>Bibliography</h3>
        <ul class="list-group">   
          <% summary_info["bibliography"].each do |bib| %>
            <li class="list-group-item">
              <%= bib %>
            </li>
          <% end %>          
        </ul>
      </div>

      <div class="well">
        <h3>Associated Samples</h3>
        <ul class="list-group">   
          <li class="list-group-item">
            <ul>
              <% summary_info["sample_ids"].each do |sam| %>
                <li><%= link_to "Sample #{sam}", sam %></li>
              <% end %>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <%= render :partial => "detailed_rec" , :locals => {:summary_info => summary_info, :details_hash => data_hashes["details_hash"]} %>
</div>

app/views/catalog/_show_chromatogram.html.erb
<% doc_presenter = show_presenter(document) %>
<%# partial to display samples documents in catalog show view -%>

<% data_hashes = chromatogram_show_data(params["id"])%>

<%= render :partial => "new_chromatogram_show" , :locals => {:data_hashes => data_hashes} %>

app/views/catalog/_show_extraction.html.erb
<% doc_presenter = show_presenter(document) %>
<%# partial to display samples documents in catalog show view -%>

<% data_hashes = extraction_show_data(params["id"])%>

<%= render :partial => "show_list" , :locals => {:data_hashes => data_hashes} %>

app/views/catalog/_show_person.html.erb
<% doc_presenter = show_presenter(document) %>
<%# partial to display samples documents in catalog show view -%>

<% data_hashes = person_show_data(params["id"])%>

<%= render :partial => "new_person_show" , :locals => {:data_hashes => data_hashes} %>

app/views/catalog/_show_product.html.erb
<% doc_presenter = show_presenter(document) %>
<%# partial to display samples documents in catalog show view -%>

<% data_hashes = product_show_data(params["id"])%>

<%= render :partial => "show_list" , :locals => {:data_hashes => data_hashes} %>

app/views/catalog/_show_site.html.erb
<% doc_presenter = show_presenter(document) %>

<% data_hashes = site_show_data(params["id"])%>

<%= render :partial => "new_site_show" , :locals => {:data_hashes => data_hashes} %>

app/views/catalog/_thumbnails.html.erb
  <div class="row">
    <% image_hash.each do |key, val| %>
        <div class="col-xs-6 col-md-3">
          
          <a href="#" class="thumbnail" data-toggle="modal" data-target="#myModal<%= key %>">
            <%= image_tag(val[1], :alt => key) %>
          </a>
          <div class="caption">
            <p><%= val[2] %></p>
          </div>
          
        </div>
      

        <div id="myModal<%= key %>" class="modal fade" role="dialog">
          <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <%= val[2] %>
              </div>
              <div class="modal-body">
                <% unless val[3] %>
                  <%= link_to image_tag(val[1], style: 'height:auto;width:100%;'), val[0], target: :_blank %>
                <% else %>
                  <div class="sketchfab-embed-wrapper"><iframe width="560" height="480" src=<%="#{val[3]}"%> frameborder="0" allowvr allowfullscreen mozallowfullscreen="true" webkitallowfullscreen="true" onmousewheel=""></iframe></div>
                <% end %>
              </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              </div>
            </div>

          </div>
       
    <% end %>
  </div>